---
title: "R_Markdown_File"
author: "RStudio"
date: "10/9/2018"
output: html_document
URL: https://github.com/Ryno2390/Intro_to_Data_Science_Capstone.git
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Project II: Submit Your Capstone Project Proposal

## Questions to Answer -- 

### What is the problem you want to solve?

Analyze the voting patterns of the US during the 2016 Presidential election - with a stretch goal of creating a prediction model of who would have won the 2016 Presidential election using FiveThirtyEight's election data. 

### Who is your client and why do they care about this problem? In other words, what will your client DO or DECIDE based on your analysis that they wouldn’t have otherwise?

Generally speakig, lobbyists seek to "back a winning horse" - i.e. they intend to contribute as much money as possible, given their contribution budget constaint, to the winning candidate. Only the winning candidate gains political power, therefore lobbysts do not wish to diluate the power of their contibution budget by donating to multiple candidates in the same race. An accurate prediction model would enable lobbyst clients to make more informed donation decisions. 

### What data are you going to use for this? How will you acquire this data?

I will use FiveThirtyEight.com's data which is readily available through Kaggle (https://www.kaggle.com/fivethirtyeight/2016-election-polls#presidential_polls.csv)

### In brief, outline your approach to solving this problem (knowing that this might change later).

My approach will bet to understand FiveThirtyEight's model and to simplify the model as much as possible to conform with the goals of this course. I will then use the data to analyze regional voting patterns, with a stretch goal of creating a simplified model that can incorporate polling data to update it's prediction of who will win the election.

### What are your deliverables? Typically, this would include code, along with a paper and/or a slide deck.

The deliverables will include:

+ A walkthrough of the model using RMarkdown
+ A detailed summary paper that analyzes regional voting trends as well as a prediction of who would win